### ISSUE TITLE
campos faltantes en el formulario persona

### ISSUE THREAD

**Issue by gitcoz** [juusechec/hrm#15]
campos por adicionar al formulario
    estrato
    direccion de vivienda
    tipo de vivienda
    cuenta bancaria
    cargar formulario de contacto de emergencia
    id eps
 tipo persona
tipo de sangre
tipo de rh
telefono 2 debe indicar que no es obligaorio

**Comment by juusechec** [comment]
está inmerso en https://github.com/juusechec/hrm/issues/27
