### ISSUE TITLE
al momento de seleccionar una persona  se despliegue menu de info a mirar

### ISSUE THREAD

**Issue by gitcoz** [juusechec/hrm#19]
al momento de encontrar una persona, desde hay se dspliegue un menu que permita selecionar  que informacion se desea ver para que de una vez se lleve la informacion de l ususario tipo informe

**Comment by juusechec** [comment]
no entiendo, leer lo que se escribió y redactarlo mejor

**Comment by juusechec** [comment]
https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/ui/collapse.html
