### ISSUE TITLE
Agregar RH como una lista desplegable

### ISSUE THREAD

**Issue by juusechec** [juusechec/hrm#28]
'choices'  => [
                    'O+' => 'O+',
                    'O-' => 'O-',
                    'A+' => 'A+',
                ],

**Comment by juusechec** [comment]
Terminar la lista con todas las posibilidades con orden alfabético.

**Comment by juusechec** [comment]
https://kidshealth.org/es/teens/blood-types-esp.html
https://symfony.com/doc/current/reference/forms/types/choice.html

**Comment by gitcoz** [comment]
solucionado en esta rama

**Comment by gitcoz** [comment]
cerrado
