### ISSUE TITLE
La llave primaria de tabla entrega_dotacion está mal

### ISSUE THREAD

**Issue by juusechec** [juusechec/hrm#3]
cambiar entrega_dotacion_pky por entrega_dotacion_id_pk

**Comment by gitcoz** [comment]
esto lo puedo realizar en geany verdad?

**Comment by juusechec** [comment]
claro que se podía, no tiene impediento

**Comment by juusechec** [comment]
Se corrige con https://github.com/juusechec/hrm/commit/8298fc61570932aca66c23a05023fce47e0dfbce
